// AdminConstants.js
export const GET_ALL_BOOKINGS_REQUEST = 'GET_ALL_BOOKINGS_REQUEST';
export const GET_ALL_BOOKINGS_SUCCESS = 'GET_ALL_BOOKINGS_SUCCESS';
export const GET_ALL_BOOKINGS_FAIL = 'GET_ALL_BOOKINGS_FAIL';

export const GET_ALL_PARTS_REQUEST = 'GET_ALL_PARTS_REQUEST';
export const GET_ALL_PARTS_SUCCESS = 'GET_ALL_PARTS_SUCCESS';
export const GET_ALL_PARTS_FAIL = 'GET_ALL_PARTS_FAIL';

export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL';

export const GET_ALL_VEHICLES_REQUEST = 'GET_ALL_VEHICLES_REQUEST';
export const GET_ALL_VEHICLES_SUCCESS = 'GET_ALL_VEHICLES_SUCCESS';
export const GET_ALL_VEHICLES_FAIL = 'GET_ALL_VEHICLES_FAIL';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const GET_DASHBOARD_STATS_REQUEST = 'GET_DASHBOARD_STATS_REQUEST';
export const GET_DASHBOARD_STATS_SUCCESS = 'GET_DASHBOARD_STATS_SUCCESS';
export const GET_DASHBOARD_STATS_FAIL = 'GET_DASHBOARD_STATS_FAIL';

export const GET_LATEST_BOOKINGS_REQUEST = 'GET_LATEST_BOOKINGS_REQUEST';
export const GET_LATEST_BOOKINGS_SUCCESS = 'GET_LATEST_BOOKINGS_SUCCESS';
export const GET_LATEST_BOOKINGS_FAIL = 'GET_LATEST_BOOKINGS_FAIL';


// Booking with Vehicle Details Constants
export const GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_REQUEST = 'GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_REQUEST';
export const GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_SUCCESS = 'GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_SUCCESS';
export const GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_FAIL = 'GET_ALL_BOOKINGS_WITH_VEHICLE_DETAILS_FAIL';

export const GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_REQUEST = 'GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_REQUEST';
export const GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_SUCCESS = 'GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_SUCCESS';
export const GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_FAIL = 'GET_LATEST_BOOKINGS_WITH_VEHICLE_DETAILS_FAIL';

export const GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_REQUEST = 'GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_REQUEST';
export const GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_SUCCESS = 'GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_SUCCESS';
export const GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_FAIL = 'GET_DASHBOARD_STATS_WITH_VEHICLE_DETAILS_FAIL';
