export const GET_APPOINTMENTS_REQUEST = 'GET_APPOINTMENTS_REQUEST';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';
export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAIL = 'UPDATE_APPOINTMENT_FAIL';
export const UPDATE_APPOINTMENT_TIME_REQUEST = 'UPDATE_APPOINTMENT_TIME_REQUEST';
export const UPDATE_APPOINTMENT_TIME_SUCCESS = 'UPDATE_APPOINTMENT_TIME_SUCCESS';
export const UPDATE_APPOINTMENT_TIME_FAIL = 'UPDATE_APPOINTMENT_TIME_FAIL';

export const ASSIGN_TECHNICIAN_REQUEST = 'ASSIGN_TECHNICIAN_REQUEST';
export const ASSIGN_TECHNICIAN_SUCCESS = 'ASSIGN_TECHNICIAN_SUCCESS';
export const ASSIGN_TECHNICIAN_FAIL = 'ASSIGN_TECHNICIAN_FAIL';

// New constants for technician services
export const GET_TECHNICIAN_SERVICES_REQUEST = 'GET_TECHNICIAN_SERVICES_REQUEST';
export const GET_TECHNICIAN_SERVICES_SUCCESS = 'GET_TECHNICIAN_SERVICES_SUCCESS';
export const GET_TECHNICIAN_SERVICES_FAIL = 'GET_TECHNICIAN_SERVICES_FAIL';