export const GET_ALL_PARTS_INVENTORY_REQUEST = 'GET_ALL_PARTS_INVENTORY_REQUEST';
export const GET_ALL_PARTS_INVENTORY_SUCCESS = 'GET_ALL_PARTS_INVENTORY_SUCCESS';
export const GET_ALL_PARTS_INVENTORY_FAIL = 'GET_ALL_PARTS_INVENTORY_FAIL';

export const ADD_PART_INVENTORY_REQUEST = 'ADD_PART_INVENTORY_REQUEST';
export const ADD_PART_INVENTORY_SUCCESS = 'ADD_PART_INVENTORY_SUCCESS';
export const ADD_PART_INVENTORY_FAIL = 'ADD_PART_INVENTORY_FAIL';

export const UPDATE_PART_INVENTORY_REQUEST = 'UPDATE_PART_INVENTORY_REQUEST';
export const UPDATE_PART_INVENTORY_SUCCESS = 'UPDATE_PART_INVENTORY_SUCCESS';
export const UPDATE_PART_INVENTORY_FAIL = 'UPDATE_PART_INVENTORY_FAIL';

export const DELETE_PART_INVENTORY_REQUEST = 'DELETE_PART_INVENTORY_REQUEST';
export const DELETE_PART_INVENTORY_SUCCESS = 'DELETE_PART_INVENTORY_SUCCESS';
export const DELETE_PART_INVENTORY_FAIL = 'DELETE_PART_INVENTORY_FAIL';